pipeline {
    agent {
        docker {
            image 'maven:3.9.0'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('chekout') {
            steps {
                git branch: 'lesson26', changelog: false, credentialsId: 'github', poll: false, url: 'https://github.com/nickolas-black/codeby-devops.git'
            }
        }
        stage('Build') {
            steps {
                dir('lesson26/app') {
                    sh 'mvn -B -DskipTests clean package'
                }
            }
        }
        stage('Test') {
            steps {
                dir('lesson26/app') {
                    sh 'mvn test'
                }
            }
            post {
                always {
                    junit 'lesson26/app/target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh 'chmod +x ./lesson26/app/jenkins/scripts/deliver.sh'
                // sh './app/jenkins/scripts/deliver.sh'
            }
        }
    }
}
