# Префикс для LAN сети
BRIDGE_NET="192.168.06."

DOMAIN="wordp"

MACHINES = {
  :centos => {
    :box_name => "centos/7",
    :host_name => "CentOS",  
    :ip_addr => BRIDGE_NET + "11",
    :cpu => 1,
    :ram => 512
  },
  :ubuntu => {
    :box_name => "ubuntu/bionic64",
    :host_name => "Ubuntu",  
    :ip_addr => BRIDGE_NET + "12",
    :cpu => 1,
    :ram => 512
  }#,
}
Vagrant.configure("2") do |config|
    MACHINES.each do |boxname, boxconfig|                   # Проходим по элементах массива "MACHINES"
        config.vm.define boxname do |box|
            box.vm.box = boxconfig[:box_name]               # Поднять машину из образа
            box.vm.host_name = boxconfig[:host_name]        # Hostname который будет присвоен VM (самой ОС)
            box.vm.usable_port_range = (2200..2250)         # Пул портов, который будет использоваться для подключения к каждый VM через 127.0.0.1
            box.vm.network "private_network", ip: boxconfig[:ip_addr]
            box.vm.provider :virtualbox do |vb|
                vb.name = boxconfig[:host_name]     # Можно перезаписать название VM в Vbox GUI
                vb.cpus = boxconfig[:cpu]
                vb.memory = boxconfig[:ram]
            end
            # SHELL
            box.vm.provision "shell", path: "scripts/add_ssh_key.sh"
            box.vm.provision "shell", path: "scripts/selinux_disable.sh"
        end
    end
end
