Vagrant.configure("2") do |config|
  
  config.vm.box = "generic/debian12"
  config.vm.box_check_update = false
  config.vm.synced_folder  "~/VAGRANT", "/vagrant"
 
config.vm.define "server-web" do |subconfig|
    # имя виртуальной машины
    subconfig.vm.provider "virtualbox" do |vb|
      vb.name = "server-web"
      vb.gui = false
      vb.memory = "1024"
    end
    # hostname виртуальной машины
    subconfig.vm.hostname = "server-web"
    # настройки сети
    subconfig.vm.network "public_network", ip: "192.168.70.108"
    # установка пакетов
    subconfig.vm.provision "shell", path: "script-server.sh"
  end
config.vm.define "client" do |subconfig|
    # имя виртуальной машины
    subconfig.vm.provider "virtualbox" do |vb|
      vb.name = "client"
      vb.gui = false
      vb.memory = "1024"
    end
    # hostname виртуальной машины
    subconfig.vm.hostname = "client"
    # настройки сети
    subconfig.vm.network "public_network", ip: "192.168.70.109"
    # установка пакетов
    subconfig.vm.provision "shell", path: "script-client.sh"
  end
end

