---
# tasks file for apache2
  - name: Check version Linux
    debug: var=ansible_os_family
 
  - block:
 
      - name: Install Apache web Server Ubuntu
        apt: 
          name: apache2 
          state: latest
 
      - name: Start Ubuntu
        service: 
          name: apache2 
          state: started
          enabled: yes
        when: ansible_os_family== "Debian"
 
    when: ansible_os_family == "Debian"
 
  - block:
 
      - name: Install Apache web Server CentOS
        yum: 
          name: httpd 
          state: latest
 
      - name: Start CentOS
        service: 
          name: httpd 
          state: started 
          enabled: yes
        when: ansible_os_family== "RedHat"
 
    when: ansible_os_family == "RedHat"
 
#  - name: Copy files in www CentOS&Debian
# ИСПРАВЛЯЕМ: src={{ source_folder }}/{{ item }} меняем на src={{ item }}
#    copy: src={{ item }} dest={{ destin_folder }} mode=0555
#    loop:
#      - "index.html"
#      - "ico.png"
#    notify:
#      - Restart Apache CentOS
#      - Restart Apache Debian