version: '3.3'
services:
  post_db:
    image: mongo:latest
    volumes:
      - post_db:/data/db
    networks:
      - monitornig

  ui:
    image: ${REGISTRY}/ui:${TAG}
    environment:
      - POST_SERVICE_HOST=post
      - POST_SERVICE_PORT=5000
      - COMMENT_SERVICE_HOST=comment
      - COMMENT_SERVICE_PORT=9292
    ports:
      - 9292:9292/tcp
    depends_on:
      - comment
      - post
    networks:
      - monitornig

  comment:
    image: ${REGISTRY}/comment:${TAG}
    environment:
      - COMMENT_DATABASE_HOST=post_db
      - COMMENT_DATABASE=comments
    depends_on:
      - post_db
    networks:
      - monitornig

  post:
    image: ${REGISTRY}/post:${TAG}
    environment:
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE=posts
    depends_on:
      - post_db
    ports:
      - "5006:5000"
    networks:
      - monitornig

volumes:
  post_db:

networks:
  monitornig: