services:
  db:
    image: mysql
    user: root
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend
    env_file:
      - mysql.env


  web:
    image: wordpress
    user: root
    restart: always
    volumes:
      - wp-data:/var/www/html
    networks:
      - backend
    links:
      - db
    env_file:
      - wordpress.env

  proxy:
    image: nginx
    volumes:
      - ./reverse_proxy.conf:/etc/nginx/conf.d/default.conf

    ports:
      - 80:80
    networks:
      - frontend
      - backend
    links:
      - web
volumes:
  db-data:
  wp-data:
  conf-nginx:

networks:
  frontend:
  backend:

