apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
    name: db
  clusterIP: None
  selector:
    app: mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pv-claim
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: mysql 
  serviceName: "mysql"
  replicas: 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: mysql # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: 'WP_PASSWORD'
        - name: MYSQL_DATABASE
          value: 'wordpress'
        - name: MYSQL_USER
          value: 'wordpress'
        - name: MYSQL_PASSWORD 
          value: 'wordpress_pass'
        ports:
        - containerPort: 3306
          name: db

        volumeMounts:
        - name: mysql-wp
          mountPath: /var/lib/mysql

      volumes:
      - name: mysql-wp
        persistentVolumeClaim:
          claimName: db-pv-claim




