# syntax=docker/dockerfile:1
FROM mysql:8

# When your application needs to interact with UTF-8.
ENV LANG C.UTF-8
ENV MYSQL_ROOT_PASSWORD=wordPressPass
ENV MYSQL_DATABASE=wordpress
ENV MYSQL_USER=wp
ENV MYSQL_PASSWORD=wppassword
